apiVersion: v1
kind: Pod
metadata:
  name: cm-inspect
  namespace: app
spec:
  restartPolicy: Never
  containers:
  - name: sh
    image: busybox
    command: ['sh','-c','ls -la /config || true; echo "--- content start ---"; sed -n "1,20p" /config/app.py || true; sleep 3600']
    volumeMounts:
    - name: db-config
      mountPath: /config
  volumes:
  - name: db-config
    configMap:
      name: frontend-db
